AWSTemplateFormatVersion: '2010-09-09'
Resources:
  Branches:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "Branches"
      AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      KeySchema:
      - AttributeName: id
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: '1'
        WriteCapacityUnits: '5'
  BranchesB2C:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "BranchesB2C"
      AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      KeySchema:
      - AttributeName: id
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: '1'
        WriteCapacityUnits: '1'
  ItemsB2C:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "ItemsB2C"
      AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      KeySchema:
      - AttributeName: id
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: '1'
        WriteCapacityUnits: '1'
  Lock:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "Lock"
      AttributeDefinitions:
      - AttributeName: name
        AttributeType: S
      KeySchema:
      - AttributeName: name
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: '1'
        WriteCapacityUnits: '1'
  Menus:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "Menus"
      AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      KeySchema:
      - AttributeName: id
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: '1'
        WriteCapacityUnits: '1'
  Restaurants:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "Restaurants"
      AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      KeySchema:
      - AttributeName: id
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: '1'
        WriteCapacityUnits: '1'
  Users:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "Users"
      AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      KeySchema:
      - AttributeName: id
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: '1'
        WriteCapacityUnits: '1'
  phototmp:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "phototmp"
      AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      KeySchema:
      - AttributeName: id
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: '1'
        WriteCapacityUnits: '1'
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
