AWSTemplateFormatVersion: '2010-09-09'
Resources:
  zonemiramenu:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: mira.menu.
      HostedZoneConfig:
        Comment: MiraMenu

  DNSGmailMX:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId:
        Ref: zonemiramenu
      RecordSets:
      - Name: mira.menu.
        Type: MX
        TTL: '3600'
        ResourceRecords:
        - 20 ALT1.ASPMX.L.GOOGLE.COM
        - 30 ALT2.ASPMX.L.GOOGLE.COM
        - 10 ASPMX.L.GOOGLE.COM
        - 40 ASPMX2.GOOGLEMAIL.COM
        - 50 ASPMX3.GOOGLEMAIL.COM

  DNSGmailTXT:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId:
        Ref: zonemiramenu
      RecordSets:
      - Name: mira.menu.
        Type: TXT
        TTL: '3600'
        ResourceRecords:
        - '"google-site-verification=2OJV5DrgHPwAt-FiPGWZ-UYn-2vVEhx6TZbFVqGDiVo"'

