AWSTemplateFormatVersion: '2010-09-09'
Resources:
  distd3t1a0tow2astkcloudfrontnet:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
        - cdn.mira.menu
        Enabled: true
        PriceClass: PriceClass_200
        DefaultCacheBehavior:
          TargetOriginId: S3-meshphoto
          ViewerProtocolPolicy: redirect-to-https
          MinTTL: 0
          AllowedMethods:
          - HEAD
          - GET
          - OPTIONS
          CachedMethods:
          - HEAD
          - GET
          - OPTIONS
          ForwardedValues:
            Cookies:
              Forward: none
        Origins:
        - DomainName: meshphoto.s3.amazonaws.com
          Id: S3-meshphoto
          S3OriginConfig: {}
        Restrictions:
          GeoRestriction:
            RestrictionType: none
            Locations: []
        ViewerCertificate:
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.1_2016
  distd15jdeimypslsicloudfrontnet:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
        - developer.mira.menu
        Enabled: true
        PriceClass: PriceClass_100
        DefaultCacheBehavior:
          TargetOriginId: S3-mesh-dev-site
          ViewerProtocolPolicy: redirect-to-https
          MinTTL: 0
          AllowedMethods:
          - HEAD
          - GET
          CachedMethods:
          - HEAD
          - GET
          ForwardedValues:
            Cookies:
              Forward: none
        Origins:
        - DomainName: mesh-dev-site.s3.amazonaws.com
          Id: S3-mesh-dev-site
          S3OriginConfig: {}
        Restrictions:
          GeoRestriction:
            RestrictionType: none
            Locations: []
        ViewerCertificate:
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.1_2016
