AWSTemplateFormatVersion: '2010-09-09'
Resources:
  dnsapimiramenu:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId:
        Ref: zonemiramenu
      RecordSets:
      - Name: api.mira.menu.
        Type: AAAA
        AliasTarget:
          HostedZoneId: Z2FDTNDATAQYW2
          DNSName: d3pmk4p926mshj.cloudfront.net
  dnsb2bapimiramenu:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId:
        Ref: zonemiramenu
      RecordSets:
      - Name: b2bapi.mira.menu.
        Type: A
        AliasTarget:
          HostedZoneId: Z2FDTNDATAQYW2
          DNSName: d3f6svzwaqjjnq.cloudfront.net


