
  s3devmiramenu:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicReadWrite
      VersioningConfiguration:
        Status: Enabled
  s3fbmiramenu:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      VersioningConfiguration:
        Status: Suspended
  s3meshdevsite:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicReadWrite
      VersioningConfiguration:
        Status: Enabled
  s3meshphoto:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      CorsConfiguration:
        CorsRules:
        - AllowedHeaders:
          - "*"
          AllowedMethods:
          - PUT
          AllowedOrigins:
          - "*"
      VersioningConfiguration:
        Status: Suspended
      Tags:
      - Key: STAGE
        Value: dev
  s3meshphotodev:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      VersioningConfiguration:
        Status: Suspended
  s3meshphotodevtmp:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicReadWrite
      CorsConfiguration:
        CorsRules:
        - AllowedHeaders:
          - "*"
          AllowedMethods:
          - PUT
          AllowedOrigins:
          - "*"
      VersioningConfiguration:
        Status: Suspended
      Tags:
      - Key: STAGE
        Value: prod
  s3meshphototmp:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicReadWrite
      CorsConfiguration:
        CorsRules:
        - AllowedHeaders:
          - "*"
          AllowedMethods:
          - PUT
          AllowedOrigins:
          - "*"
      VersioningConfiguration:
        Status: Suspended
      Tags:
      - Key: STAGE
        Value: prod
  s3miramenu:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicReadWrite
      VersioningConfiguration:
        Status: Enabled


